[ebay_sandbox]
dev_id = "1ce4d5e8-6cac-4da8-a6a3-3e540254c813"
client_id = st.secrets["EBAY_CLIENT_ID"]
client_secret = "SBX-8ea2d7573318-9ca3-4c99-b515-236f"
environment = "sandbox"
auth_url = "https://api.sandbox.ebay.com/identity/v1/oauth2/token"
api_base_url = "https://api.sandbox.ebay.com"
